# Generated by Django 5.2.16 on 2026-07-22 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('cabana', 'Cabaña'), ('habitacion', 'Habitación'), ('estudio', 'Estudio')], max_length=20)),
                ('modalidad', models.CharField(choices=[('hospedaje', 'Hospedaje'), ('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_precio', models.CharField(choices=[('noche', '/ noche'), ('mes', '/ mes'), ('total', 'total')], max_length=10)),
                ('capacidad_personas', models.PositiveIntegerField(blank=True, null=True)),
                ('habitaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('banos', models.PositiveIntegerField(blank=True, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/')),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='De 1 a 5')),
                ('comentario', models.TextField(blank=True)),
                ('cal_limpieza', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cal_ubicacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cal_comunicacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
    ]
