# Generated by Django 5.2.16 on 2026-07-23 03:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('ambos', 'Ambos')], default='ambos', max_length=20)),
                ('comision_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('propiedades_activas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('basica', 'Básica'), ('premium', 'Premium'), ('exterior', 'Exterior')], default='basica', max_length=20)),
            ],
            options={
                'verbose_name': 'Amenidad',
                'verbose_name_plural': 'Amenidades',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.PositiveIntegerField()),
                ('tipo_referencia', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('reserva', 'Reserva')], max_length=20)),
                ('tipo_doc', models.CharField(choices=[('contrato', 'Contrato'), ('escritura', 'Escritura'), ('recibo', 'Recibo'), ('identificacion', 'Identificación')], max_length=20)),
                ('url_archivo', models.URLField(max_length=500)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.PositiveIntegerField()),
                ('tipo_referencia', models.CharField(choices=[('reserva', 'Reserva'), ('arriendo', 'Arriendo'), ('venta', 'Venta')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('concepto', models.CharField(choices=[('canon', 'Canon'), ('deposito', 'Depósito'), ('reserva', 'Reserva'), ('cuota_inicial', 'Cuota inicial')], max_length=20)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('cabana', 'Cabaña'), ('habitacion', 'Habitación'), ('apartamento', 'Apartamento'), ('estudio', 'Estudio')], max_length=20)),
                ('modalidad', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('hospedaje_corto', 'Hospedaje corto')], max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_precio', models.CharField(choices=[('total', 'Total'), ('mes', 'Por mes'), ('noche', 'Por noche')], max_length=10)),
                ('capacidad_personas', models.PositiveIntegerField(blank=True, null=True)),
                ('habitaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('banos', models.PositiveIntegerField(blank=True, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='core.agente')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_foto', models.ImageField(upload_to='propiedades/')),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('host', 'Anfitrión'), ('agente', 'Agente'), ('comprador', 'Comprador'), ('viajero', 'Viajero')], default='viajero', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_set', related_query_name='usuario', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_set', related_query_name='usuario', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReservaHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('num_huespedes', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('tipo_alojamiento', models.CharField(blank=True, choices=[('hospedaje', 'Hospedaje'), ('cabana', 'Cabaña')], max_length=20, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.propiedad')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Reserva de hospedaje',
                'verbose_name_plural': 'Reservas de hospedaje',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_referencia', models.PositiveIntegerField()),
                ('tipo_referencia', models.CharField(choices=[('reserva', 'Reserva'), ('arriendo', 'Arriendo')], max_length=20)),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('cal_limpieza', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cal_ubicacion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cal_comunicacion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.propiedad')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='ProcesoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('oferta', 'Oferta'), ('negociacion', 'Negociación'), ('aprobado', 'Aprobado'), ('escritura', 'Escritura'), ('cerrado', 'Cerrado')], default='oferta', max_length=20)),
                ('fecha_oferta', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.agente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.propiedad')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_comprador', to='core.usuario')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_vendedor', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Proceso de venta',
                'verbose_name_plural': 'Procesos de venta',
            },
        ),
        migrations.CreateModel(
            name='OfertaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_oferta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mensaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('contraoferta', 'Contraoferta')], default='enviada', max_length=20)),
                ('fecha_oferta', models.DateField(auto_now_add=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.procesoventa')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Oferta de compra',
                'verbose_name_plural': 'Ofertas de compra',
            },
        ),
        migrations.CreateModel(
            name='ContratoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('canon_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('terminado', 'Terminado')], default='borrador', max_length=20)),
                ('duracion_meses', models.PositiveIntegerField(blank=True, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='core.propiedad')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_arrendatario', to='core.usuario')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_propietario', to='core.usuario')),
            ],
            options={
                'verbose_name': 'Contrato de arriendo',
                'verbose_name_plural': 'Contratos de arriendo',
            },
        ),
        migrations.AddField(
            model_name='agente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('precio_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'unique_together': {('propiedad', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadAmenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.amenidad')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
            options={
                'verbose_name': 'Amenidad de propiedad',
                'verbose_name_plural': 'Amenidades de propiedades',
                'unique_together': {('propiedad', 'amenidad')},
            },
        ),
    ]
