# Generated by Django 5.2.16 on 2026-07-23 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anfitrion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('biografia', models.TextField(blank=True)),
                ('propiedades_activas', models.PositiveIntegerField(default=0)),
                ('superhost', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anfitrion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anfitrión',
                'verbose_name_plural': 'Anfitriones',
            },
        ),
    ]
